### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by Bishnukt** [hemant087/Data_Structure_and_Algorithm_practice#12]
Hey Hemant, I just checked out your repository and noticed that you've also pushed .exe files with the codes. It'll look better and more organized if you include a **.gitignore** file with ***.exe** in it, then .exe files won't be tracked.

**Comment by hemant087** [comment]
Hey thanks 😊,, I'm new here, i don't have much idea about .gitignore  or GitHub,,, although I spend approx two hours to add .gitignore file ,, but it's not working,, could you help me

**Comment by hemant087** [comment]
Thanks, it's working, i was also looking for this type of function which wipes out all the exe file

**Comment by Bishnukt** [comment]
> Hey thanks 😊,, I'm new here, i don't have much idea about .gitignore  or GitHub,,, although I spend approx two hours to add .gitignore file ,, but it's not working,, could you help me 

Yeah u've added the .gitignore file, that should do the work in future, but for now, you must remove the .exe files from the repository manually. If you're using git from command line, you can just use this command in each directories **git rm --cached *exe** , then commit and push the changes, else you can delete it manually from github too.

**Comment by Bishnukt** [comment]
> Thanks, it's working, i was also looking for this type of function which wipes out all the exe file

Good to hear that, closing this issue then.
